tools:
  fzf:
    version: "0.46.1"
    url: "https://github.com/junegunn/fzf/releases/download/0.46.1/fzf-0.46.1-linux_amd64.tar.gz"
  ripgrep:
    version: "14.1.0"
    package: "ripgrep"
  bat:
    version: "latest"
    package: "bat"
  exa:
    version: "latest"
    url: "https://github.com/ogham/exa/releases/latest/download/exa-linux-x86_64-v0.10.1.zip"
