tools:
  kubectl:
    version: "1.29.2"
    url: "https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl"
  helm:
    version: "latest"
    install_script: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
  k9s:
    version: "latest"
    url: "https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz"
